language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install pep8"

env:
    MYAPP_SECRET_KEY=travis
    
before_script:
  - mysql -e 'create database poll;'    
  - "pep8 --exclude='agiliq_app/migrations' poll pollapp/"
# command to run tests
script: python manage.py test
